version: '3.8'

services:
  
  orders-db:
    image: postgres:15.3
    restart: always
    container_name: auth-ms
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - ./postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432